prefix dbo: <http://dbpedia.org/ontology/>
prefix dbp: <http://dbpedia.org/property/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label ?namePlace ?combatant ?date
WHERE {
		?conflit rdf:type dbo:MilitaryConflict .
		?conflit dbo:place ?place.
		?place dbp:commonName ?namePlace.
		?conflit rdfs:label ?label.
		?conflit dbo:combatant ?combatant.
		?conflit dbo:date ?date
FILTER regex(?combatant, "^[a-z]|^[A-Z]")
FILTER (lang(?label)='en')
FILTER (lang(?namePlace)='en')
} LIMIT 500
